apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocm
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: git@github.com:iagouvea07/platform-multicluster.git
      targetRevision: main
      path: ocm/resources/
    - repoURL: https://open-cluster-management.io/helm-charts
      chart: argocd-pull-integration
      targetRevision: 0.29.0
      helm:
        releaseName: argocd-pull-integration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true