apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: argocd
  namespace: spoke-1 
spec:
  installNamespace: open-cluster-management-agent-addon
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: argocd
  namespace: spoke-2 
spec:
  installNamespace: open-cluster-management-agent-addon